#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 22, 2021 01:29:30 PM +03  platform: Windows NT
import inspect
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    print(f'[SUP][LOG] in {inspect.stack()[0][3]}')
    print(f'[SUP][LOG] in {inspect.stack()[1][3]}')
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    print(f'[SUP][LOG] in {inspect.stack()[0][3]}')
    print(f'[SUP][LOG] in {inspect.stack()[1][3]}')
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    print(f'[SUP][LOG] in {inspect.stack()[0][3]}')
    print(f'[SUP][LOG] in {inspect.stack()[1][3]}')
    import temp_des
    temp_des.vp_start_gui()




