#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 25, 2021 08:26:26 PM +03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import main_support

def perc(n,p):
    return (n / 100) * p

WINDOW_HSIZE = 710
WINDOW_VSIZE = 450
TREE_HSIZE = 610
TREE_VSIZE = 200
COLUMNS_SIZE = [perc(TREE_HSIZE, 10)] + [perc(TREE_HSIZE,18)] * 5


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainWindow (root)
    main_support.init(root, top)
    root.mainloop()

w = None
def create_MainWindow(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_MainWindow(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = MainWindow (w)
    main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainWindow():
    global w
    w.destroy()
    w = None

class MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("710x450+382+78")
        top.minsize(120, 1)
        top.maxsize(1684, 1031)
        top.resizable(1,  1)
        top.title("Bells")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.style.configure('Treeview',  font="TkDefaultFont")
        self.main_tree = ScrolledTreeView(top)
        self.main_tree.place(relx=0.07, rely=0.489, relheight=0.444
                , relwidth=0.859)
        self.main_tree.configure(columns="Col1 Col2 Col3 Col4 Col5 Col6")
        self.main_tree.configure(show="headings")
        self.main_tree.configure(selectmode='browse')
        # build_treeview_support starting.
        self.main_tree.heading("#0",text="Tree")
        self.main_tree.heading("#0",anchor="center")
        self.main_tree.column("#0",width="225")
        self.main_tree.column("#0",minwidth="20")
        self.main_tree.column("#0",stretch="1")
        self.main_tree.column("#0",anchor="w")
        self.main_tree.heading("Col1",text="№")
        self.main_tree.heading("Col1",anchor="center")
        self.main_tree.column("Col1",width="20")
        self.main_tree.column("Col1",minwidth="20")
        self.main_tree.column("Col1",stretch="1")
        self.main_tree.column("Col1",anchor="w")
        self.main_tree.heading("Col2",text="Schedule")
        self.main_tree.heading("Col2",anchor="center")
        self.main_tree.column("Col2",width="100")
        self.main_tree.column("Col2",minwidth="20")
        self.main_tree.column("Col2",stretch="1")
        self.main_tree.column("Col2",anchor="w")
        self.main_tree.heading("Col3",text="start_prev")
        self.main_tree.heading("Col3",anchor="center")
        self.main_tree.column("Col3",width="121")
        self.main_tree.column("Col3",minwidth="20")
        self.main_tree.column("Col3",stretch="1")
        self.main_tree.column("Col3",anchor="w")
        self.main_tree.heading("Col4",text="start_next")
        self.main_tree.heading("Col4",anchor="center")
        self.main_tree.column("Col4",width="120")
        self.main_tree.column("Col4",minwidth="20")
        self.main_tree.column("Col4",stretch="1")
        self.main_tree.column("Col4",anchor="w")
        self.main_tree.heading("Col5",text="end_prev")
        self.main_tree.heading("Col5",anchor="center")
        self.main_tree.column("Col5",width="118")
        self.main_tree.column("Col5",minwidth="20")
        self.main_tree.column("Col5",stretch="1")
        self.main_tree.column("Col5",anchor="w")
        self.main_tree.heading("Col6",text="end_next")
        self.main_tree.heading("Col6",anchor="center")
        self.main_tree.column("Col6",width="112")
        self.main_tree.column("Col6",minwidth="20")
        self.main_tree.column("Col6",stretch="1")
        self.main_tree.column("Col6",anchor="w")

        self.label_prazdnik = tk.LabelFrame(top)
        self.label_prazdnik.place(relx=0.507, rely=0.022, relheight=0.456
                , relwidth=0.424)
        self.label_prazdnik.configure(relief='groove')
        self.label_prazdnik.configure(foreground="black")
        self.label_prazdnik.configure(text='''P R A Z D N I K''')
        self.label_prazdnik.configure(background="#d9d9d9")
        self.label_prazdnik.configure(highlightbackground="#d9d9d9")
        self.label_prazdnik.configure(highlightcolor="black")

        self.but_pl_select = tk.Button(self.label_prazdnik)
        self.but_pl_select.place(relx=0.066, rely=0.195, height=44, width=127
                , bordermode='ignore')
        self.but_pl_select.configure(activebackground="#ececec")
        self.but_pl_select.configure(activeforeground="#000000")
        self.but_pl_select.configure(background="#d9d9d9")
        self.but_pl_select.configure(disabledforeground="#a3a3a3")
        self.but_pl_select.configure(foreground="#000000")
        self.but_pl_select.configure(highlightbackground="#d9d9d9")
        self.but_pl_select.configure(highlightcolor="black")
        self.but_pl_select.configure(pady="0")
        self.but_pl_select.configure(text='''Select playlist''')

        self.but_pl_clear = tk.Button(self.label_prazdnik)
        self.but_pl_clear.place(relx=0.066, rely=0.58, height=44, width=127
                , bordermode='ignore')
        self.but_pl_clear.configure(activebackground="#ececec")
        self.but_pl_clear.configure(activeforeground="#000000")
        self.but_pl_clear.configure(background="#d9d9d9")
        self.but_pl_clear.configure(disabledforeground="#a3a3a3")
        self.but_pl_clear.configure(foreground="#000000")
        self.but_pl_clear.configure(highlightbackground="#d9d9d9")
        self.but_pl_clear.configure(highlightcolor="black")
        self.but_pl_clear.configure(pady="0")
        self.but_pl_clear.configure(text='''Clear playlist''')

        self.but_pl_shuffle = tk.Button(self.label_prazdnik)
        self.but_pl_shuffle.place(relx=0.525, rely=0.195, height=44, width=127
                , bordermode='ignore')
        self.but_pl_shuffle.configure(activebackground="#ececec")
        self.but_pl_shuffle.configure(activeforeground="#000000")
        self.but_pl_shuffle.configure(background="#d9d9d9")
        self.but_pl_shuffle.configure(disabledforeground="#a3a3a3")
        self.but_pl_shuffle.configure(foreground="#000000")
        self.but_pl_shuffle.configure(highlightbackground="#d9d9d9")
        self.but_pl_shuffle.configure(highlightcolor="black")
        self.but_pl_shuffle.configure(pady="0")
        self.but_pl_shuffle.configure(text='''Shuffle playlist''')

        self.label_default = tk.LabelFrame(top)
        self.label_default.place(relx=0.07, rely=0.022, relheight=0.456
                , relwidth=0.424)
        self.label_default.configure(relief='groove')
        self.label_default.configure(foreground="black")
        self.label_default.configure(text='''D E F A U L T''')
        self.label_default.configure(background="#d9d9d9")
        self.label_default.configure(highlightbackground="#d9d9d9")
        self.label_default.configure(highlightcolor="black")

        self.but_select_mp3 = tk.Button(self.label_default)
        self.but_select_mp3.place(relx=0.066, rely=0.195, height=44, width=127
                , bordermode='ignore')
        self.but_select_mp3.configure(activebackground="#ececec")
        self.but_select_mp3.configure(activeforeground="#000000")
        self.but_select_mp3.configure(background="#d9d9d9")
        self.but_select_mp3.configure(disabledforeground="#a3a3a3")
        self.but_select_mp3.configure(foreground="#000000")
        self.but_select_mp3.configure(highlightbackground="#d9d9d9")
        self.but_select_mp3.configure(highlightcolor="black")
        self.but_select_mp3.configure(pady="0")
        self.but_select_mp3.configure(text='''Select MP3''')

        self.but_delete_task = tk.Button(self.label_default)
        self.but_delete_task.place(relx=0.066, rely=0.585, height=44, width=127
                , bordermode='ignore')
        self.but_delete_task.configure(activebackground="#ececec")
        self.but_delete_task.configure(activeforeground="#000000")
        self.but_delete_task.configure(background="#d9d9d9")
        self.but_delete_task.configure(disabledforeground="#a3a3a3")
        self.but_delete_task.configure(foreground="#000000")
        self.but_delete_task.configure(highlightbackground="#d9d9d9")
        self.but_delete_task.configure(highlightcolor="black")
        self.but_delete_task.configure(pady="0")
        self.but_delete_task.configure(text='''Delete task''')

        self.but_bind_file = tk.Button(self.label_default)
        self.but_bind_file.place(relx=0.528, rely=0.195, height=44, width=127
                , bordermode='ignore')
        self.but_bind_file.configure(activebackground="#ececec")
        self.but_bind_file.configure(activeforeground="#000000")
        self.but_bind_file.configure(background="#d9d9d9")
        self.but_bind_file.configure(disabledforeground="#a3a3a3")
        self.but_bind_file.configure(foreground="#000000")
        self.but_bind_file.configure(highlightbackground="#d9d9d9")
        self.but_bind_file.configure(highlightcolor="black")
        self.but_bind_file.configure(pady="0")
        self.but_bind_file.configure(text='''Bind file''')

        self.but_clear_tasks = tk.Button(self.label_default)
        self.but_clear_tasks.place(relx=0.532, rely=0.585, height=44, width=127
                , bordermode='ignore')
        self.but_clear_tasks.configure(activebackground="#ececec")
        self.but_clear_tasks.configure(activeforeground="#000000")
        self.but_clear_tasks.configure(background="#d9d9d9")
        self.but_clear_tasks.configure(disabledforeground="#a3a3a3")
        self.but_clear_tasks.configure(foreground="#000000")
        self.but_clear_tasks.configure(highlightbackground="#d9d9d9")
        self.but_clear_tasks.configure(highlightcolor="black")
        self.but_clear_tasks.configure(pady="0")
        self.but_clear_tasks.configure(text='''Clear tasks''')

        self.status_time = tk.Frame(top)
        self.status_time.place(relx=0.0, rely=0.947, relheight=0.056
                , relwidth=0.5)
        self.status_time.configure(relief='groove')
        self.status_time.configure(borderwidth="2")
        self.status_time.configure(relief="groove")
        self.status_time.configure(background="#d9d9d9")
        self.status_time.configure(highlightbackground="#d9d9d9")
        self.status_time.configure(highlightcolor="black")

        self.status_all = tk.Frame(top)
        self.status_all.place(relx=0.501, rely=0.947, relheight=0.056
                , relwidth=0.5)
        self.status_all.configure(relief='groove')
        self.status_all.configure(borderwidth="2")
        self.status_all.configure(relief="groove")
        self.status_all.configure(background="#d9d9d9")
        self.status_all.configure(highlightbackground="#d9d9d9")
        self.status_all.configure(highlightcolor="black")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





